apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.212045153Z
    description: BlueCompute Auth Microservice
    digest: 6a0d412626630e552ba7688f8be9e1a6a24849a07319f0ecef7c9efb8a5670d0
    name: auth
    urls:
    - auth-0.1.0.tgz
    version: 0.1.0
  auth-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.215022911Z
    description: BlueCompute Auth Microservice
    digest: 8d48c00bb1f5777f544ae43ddac3a70c8c241ae7936b444670854bc989546269
    name: auth-ce
    urls:
    - auth-ce-0.1.0.tgz
    version: 0.1.0
  catalog:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.219044527Z
    description: BlueCompute Catalog Microservice
    digest: 45c67d0744fee5b5fe69a06234cc1f08457c549b7885fff99afc82a55913abea
    name: catalog
    urls:
    - catalog-0.1.1.tgz
    version: 0.1.1
  catalog-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.221932692Z
    description: BlueCompute Catalog Microservice
    digest: f5e1061712553532c6267cd007bc14f41bdf2a8064430f0dce197b74ebcdda5a
    name: catalog-ce
    urls:
    - catalog-ce-0.1.1.tgz
    version: 0.1.1
  catalog-elasticsearch:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.226306889Z
    description: BlueCompute ElasticSearch for Catalog
    digest: 9708bf2b63f83201dfadbdab8d4c601ce3f35fb6bddb6183989fd773db5b43b6
    name: catalog-elasticsearch
    urls:
    - catalog-elasticsearch-0.1.1.tgz
    version: 0.1.1
  customer:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.230722936Z
    description: BlueCompute Customer Microservice
    digest: c637de164bd9267688eddd122476551f84712cf14f55f2f0681cb20770b70b5b
    name: customer
    urls:
    - customer-0.1.0.tgz
    version: 0.1.0
  customer-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.234624495Z
    description: BlueCompute Customer Microservice
    digest: e09230f051a9875608ef6206f17078340c57ee344f5b0aa76825a0a6a8525b95
    name: customer-ce
    urls:
    - customer-ce-0.1.0.tgz
    version: 0.1.0
  grafana-bc:
  - created: 2017-07-10T21:32:49.23835346Z
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 41e9b7e0e2532428ac273edf9ef0e0980199cf097dd9b76a9239045752a5c040
    engine: gotpl
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    maintainers:
    - email: zanhsieh@gmail.com
      name: Ming Hsieh
    - email: brobert@il.ibm.com
      name: Robert Barron
    name: grafana-bc
    sources:
    - https://github.com/grafana/grafana
    urls:
    - grafana-bc-0.3.1.tgz
    version: 0.3.1
  ibmcase-mysql:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.241648341Z
    description: resilient MySQL deployment
    digest: c34114edbcd45db26ec266e84f45f5b74b8cb47c6b61f92db1bc2e60e71c449f
    name: ibmcase-mysql
    urls:
    - ibmcase-mysql-0.1.0.tgz
    version: 0.1.0
  inventory:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.245477187Z
    description: BlueCompute Inventory Microservice
    digest: 321d0101cfdae784fd1b809064684006d4b7b49cdb2ade98233f9fb83909d8b3
    name: inventory
    urls:
    - inventory-0.1.1.tgz
    version: 0.1.1
  inventory-backup:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.24845045Z
    description: BlueCompute Inventory Backup Microservice
    digest: 540023446b8e4d4ebc9915e13198c19629ca595d2d138384a19a5eae7085f260
    engine: gotpl
    name: inventory-backup
    urls:
    - inventory-backup-0.1.1.tgz
    version: 0.1.1
  inventory-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.251278087Z
    description: BlueCompute Inventory Microservice
    digest: 8e4607de39a5568564b94f0a7b6ec472cf616e701dd854a7b480b52d38d23eed
    name: inventory-ce
    urls:
    - inventory-ce-0.1.1.tgz
    version: 0.1.1
  inventory-mysql:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.254274523Z
    description: BlueCompute Inventory Microservice
    digest: 22037ff39c0e00759846e7cccb6def8711aba7156f4715ae7f1578b28e6280e5
    engine: gotpl
    name: inventory-mysql
    urls:
    - inventory-mysql-0.1.1.tgz
    version: 0.1.1
  orders:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.257381327Z
    description: Bluecompute Orders Microservice
    digest: 92bd6a7204267f6b49d326db1ce6b7353d52c1578d0ffec73c003553df1154af
    name: orders
    urls:
    - orders-0.1.0.tgz
    version: 0.1.0
  orders-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.260120269Z
    description: Bluecompute Orders Microservice
    digest: d881a471874b2038e2abe086607c7a21b9e73bf847574f25b47af03528f83954
    name: orders-ce
    urls:
    - orders-ce-0.1.0.tgz
    version: 0.1.0
  web:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.263122498Z
    description: BlueCompute Web BFF app
    digest: 8731518a78d61419741d667830c7f86e9265242dbafa3e2183062e29b10a3776
    name: web
    urls:
    - web-0.1.0.tgz
    version: 0.1.0
  web-ce:
  - apiVersion: v1
    created: 2017-07-10T21:32:49.265940646Z
    description: BlueCompute Web BFF app
    digest: 9d62d4b5f4f6c64634d45bc14f8c3470070544c3a8e6b9c1375b2d2bac726799
    name: web-ce
    urls:
    - web-ce-0.1.0.tgz
    version: 0.1.0
generated: 2017-07-10T21:32:49.208753768Z
